version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: jenkins
    volumes:
      - ~/Projects/volumes/jenkins/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
volumes:
    jenkins_home: